NativeScript/nativescript-imagepicker

source/package.json

Fix plugin's package.json to have:
* correct nativescript key - current nateivescript key had been copy-pasted from project. Plugin's nativescript key has different structure.
* set required version of `tns-core-modules` to use `^`, so new versions will be used when they are released.

Fix plugin's package.json

---

nativescript-imagepicker/images.ios.ts
nativescript-imagepicker/images.xml
nativescript-imagepicker/package.json

This fixes the issue #38 - it looks like pull #39 also fixes it the same way; however my layout looks like Apples (4 up on standard phone) & more optimized and has a lot less white space...   It also adjusts the number of columns on larger devices to eliminate as much white space as possible...
Mine: 
#39's:

Fix slow & crashing images (Master Branch)

---

examples/ExampleImgPick/package.json
nativescript-imagepicker/package.json

In order to be a webpack-discoverable module, we need to remove the `.js` suffix in the package.json `main` attribute. This allows webpack to correctly look for `my-module.android.js` or `my-module.ios.js`.
Details here:
http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html#referencing-platform-specific-modules-from-packagejson

Supporting webpack

---

nativescript-imagepicker/index.d.ts
nativescript-imagepicker/viewmodel.ios.ts

For iOS you can now provide options for doneText, cancelText and albumsText to allow translation strings for the album buttons.

iOS: Parameters for button texts

---

examples/ExampleImgPick/package.json
examples/ExampleImgPickNG/package.json

Include `nativescirpt telerik ui` as a dependency. It will not be added while installing the plugin.

Include nativescirpt telerik ui as a dependency.

---

src/package.json
src/scripts/require-nativescript-telerik-ui.js

Hi,
I saw #50 and wondered if a little `postinstall` script could fix it. Turns out it does, so please review this PR.
What it does is:
- Move the `nativescript-telerik-ui` dependency to devDependencies (so users won't automatically get the non-pro version as well in case they already have the pro version installed).
- Trigger a `postinstall` script that checks whether or not either `nativescript-telerik-ui` or `nativescript-telerik-ui-pro` is installed.
- If so: do nothing.
- If not: add `nativescript-telerik-ui` to the project's `package.json`, with the version listed in the plugin `package.json`'s devDependencies. The reason is this way the user can upgrade to `nativescript-telerik-ui-pro` at a later time if he so chooses, simply by changing the project's `package.json` dependency to …

Play nice with nativescript-telerik-ui-pro

---

src/index.d.ts

#41 introduced the option to have the plugin show the newest images first on iOS, but there was no update to the TS definition file so I'm currently having a hard time using that cool feature in my TS app.
#81 also adds this but that PR tries to fix multiple things so that may explain why it's not merged yet.

Added 'newestFirst' to typings

---

demo/README.md

Give simple instructions on how to run the demo, so users can evaluate the plugin more easily.

update demo instructions

---

README.md
src/imagepicker.ios.ts

Fix aspect ratio issue on iOS where resized images were filled out instead of maintaining the aspect ratio. Also added example for scaling images to the docs.

Fix aspect ratio issue on iOS & add scaling example to docs

---

README.md
demo/app/main-page.ts
demo/app/main-page.xml
src/imagepicker.ios.ts
src/index.d.ts
src/package.json

This is an extension of PR #114

(feat): Add option for iOS image aspect ratio. Default is `fill`.

---

nativescript-imagepicker/index.d.ts

Fixed up `index.d.ts` to work with webpack and also added `newestFirst` into Options. This indicates if images should be ordered as newest first

Fixes for webpack and added newestFirst into Options model

---

src/imagepicker.android.ts

If targetSize was null or undefined then the 
`while (!(this.matchesSize(targetSize, outWidth) ||
this.matchesSize(targetSize, outHeight)))`
created an infinite loop

Check getImage options on android

---

.github/pull_request_template.md
CONTRIBUTING.md
DevelopmentWorkflow.md
README.md
src/package.json

- update readme with more info about the forums and slack
- add PR template
- add CONTRIBUTING.md and DevelopmentWorkflow.md

docs: update docs

---

README.md
src/images.ios.ts
src/images.xml
src/package.json

Since recently the nativescript-pro-ui package was split in single component packages. This commit replaces the monolityhic package with the one for list-view

chore: migrate to split list-view package

---

demo-angular/package.json
src/imagepicker.android.ts

Currently user is allowed to pick an image from external storage like SDCard, Google Drive, etc. but when an image is selected, its filename is not correctly resolved by the plugin and the image is not displayed in the demo.
The user is allowed to pick only images from local storage, so when any image is selected it can be correctly visualised by the application.
Related with #189.

chore: allow only local files for picking

---

src/imagepicker.ios.ts
src/package.json

Fix for displaying blurred images in image picker when the root view of the app is any layout nesting TabView. 
Branch on which there is a reproduced bad behaviour is here:
https://github.com/JakubPawlak/nativescript-imagepicker/tree/blur
In some specific cases, image picker is showing blurred images.
https://github.com/NativeScript/nativescript-imagepicker/issues/195
No blurred images.
Fixes #195
No migration steps.

fix(ios): no blurred images in image picker

---

src/imagepicker.ios.ts

manages to keep memory usage low, especially when picking a lot of images, fixes #222

fix: call GC upon image picking

---

src/imagepicker.ios.ts

addresses #251 
The issue seems to be caused by freeing up the delegate instance on the native side ([stored as weak](https://github.com/questbeat/QBImagePicker/blob/93ba9d54016722e82d46e1cf19750dd285b81a81/QBImagePicker/QBImagePickerController.h#L34)). Storing it in the global scope on the JS side prevents the runtime from collecting it.

fix: register delegate in global scope on creation, clear it when dismissed

---

src/package.json

This plugin uses 1.2.* version of nativescript-permissions, which is using the legacy support library
This plugin uses 1.3.* version of nativescript-permissions, which supports both AndroidX and the legacy support library
Related with: https://github.com/NativeScript/nativescript-imagepicker/issues/263

chore: update permissions version

---

src/imagepicker.android.ts
src/imagepicker.common.ts
src/imagepicker.ios.ts

There is a ImagePickerMediaType enum that seems like it can be added to the [demo app](https://github.com/NativeScript/nativescript-imagepicker/blob/master/demo/app/main-view-model.ts#L71):
```
let context = imagepicker.create({ mode: "single", mediaType: imagepicker.ImagePickerMediaType.Image });
```
However when I run the app, it crashes with` Cannot read property 'Image' of undefined`
App doesn't crash with the above changes
Related with https://github.com/NativeScript/nativescript-imagepicker/issues/285.

fix: not exported type

---

README.md
src/imagepicker.android.ts
src/index.d.ts

@xuhcc created [a PR](https://github.com/NativeScript/nativescript-imagepicker/pull/277):
`mediaType` option only works on iOS.
`mediaType` option supported on Android too.
Related with: #175.

feat(android): add support for mediaType option for android devices

---

README.md
src/imagepicker.android.ts
src/imagepicker.common.ts
src/index.d.ts

Internal and external storage may not be shown by default in Android file chooser.
The new `showAdvanced` option forces the file chooser to show these locations. However, under the hood, it uses an undocumented android function, so the warning was added to readme.
I also removed two broken links from TOC.

feat(android): add option for showing internal/external storage

---

src/imagepicker.android.ts
src/index.d.ts

Following the discussion in #301
On Android, even when media type is set to `ImagePickerMediaType.Any`, it is not possible to select any file except image or video, everything else is greyed out.
Behavior remains the same, but the new code structure would allow customization of picker behavior in subclasses, for example:
```typescript
class FilePicker extends ImagePicker {
get mimeTypes() {
let mimeTypes = Array.create(java.lang.String, 1);
mimeTypes[0] = '*/*';
return mimeTypes;
}
}
```

refactor(android): add mimeTypes property to ImagePicker class

---

src/imagepicker.android.ts

Picking files from SDCARD location doesn't work. Here's an example of the selection result:
```
[{
"_observers": {},
"_options": {
"keepAspectRatio": true,
"autoScaleFactor": true
},
"_android": ""
}]
```
Now it's working (at least in some cases).

fix(android): Fix picking from 'SDCARD' location
